import { readdirSync, readFileSync } from "node:fs";
import { extname, join, resolve } from "node:path";

const root = resolve();
const packageFiles = [
  ...listPackageFiles(join(root, "apps")),
  ...listPackageFiles(join(root, "packages"))
];
const semverPattern = /^\d+\.\d+\.\d+$/;
const failures: string[] = [];

const rootPackage = readJson<{ version?: string }>(join(root, "package.json"));
const rootVersion = rootPackage.version;

if (!rootVersion || !semverPattern.test(rootVersion)) {
  failures.push(`root package.json version must be three numeric segments, received ${rootVersion ?? "<missing>"}`);
}

for (const file of packageFiles) {
  const packageJson = readJson<{ name?: string; version?: string }>(file);
  const label = packageJson.name ?? relative(file);
  if (packageJson.version !== undefined) {
    failures.push(`${label} must not define version; root package.json is the only hand-authored version source`);
  }
}

const projectVersionFile = join(root, "packages/core/src/project-version.ts");
const projectVersionSource = readFileSync(projectVersionFile, "utf8");
const projectVersion = projectVersionSource.match(/PROJECT_VERSION\s*=\s*"([^"]+)"/)?.[1];
if (!projectVersion || !semverPattern.test(projectVersion)) {
  failures.push(`PROJECT_VERSION must be three numeric segments, received ${projectVersion ?? "<missing>"}`);
} else if (rootVersion && projectVersion !== rootVersion) {
  failures.push(`PROJECT_VERSION ${projectVersion} must match root version ${rootVersion}`);
}
if (rootVersion && projectVersionSource !== expectedProjectVersionSource(rootVersion)) {
  failures.push("packages/core/src/project-version.ts must be generated from root package.json by pnpm version:sync");
}

if (failures.length) {
  console.error(failures.join("\n"));
  process.exit(1);
}

console.log(`Checked root version ${rootVersion}, ${packageFiles.length} workspace packages, and generated PROJECT_VERSION.`);

function listPackageFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory() && !["node_modules", "dist", ".git"].includes(entry.name)) return listPackageFiles(path);
    if (entry.isFile() && entry.name === "package.json" && extname(entry.name) === ".json") return [path];
    return [];
  });
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

function relative(path: string): string {
  return path.slice(root.length + 1);
}

function expectedProjectVersionSource(version: string): string {
  return `// Generated from root package.json by scripts/sync-project-version.ts.
// Do not edit this file directly.
export const PROJECT_VERSION = "${version}";
`;
}
