import { writeFileSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve();
const rootPackage = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { version?: string };

if (!rootPackage.version || !/^\d+\.\d+\.\d+$/.test(rootPackage.version)) {
  throw new Error(`root package.json version must be three numeric segments, received ${rootPackage.version ?? "<missing>"}`);
}

writeFileSync(join(root, "packages/core/src/project-version.ts"), projectVersionSource(rootPackage.version));

function projectVersionSource(version: string): string {
  return `// Generated from root package.json by scripts/sync-project-version.ts.
// Do not edit this file directly.
export const PROJECT_VERSION = "${version}";
`;
}
